version: 2.1

orbs:
  go-module: timakin/go-module@0.0.5
  reviewdog: zchee/reviewdog@0.0.1

executors:
  default:
    working_directory: /go/src/github.com/timakin/goaccessor
    docker:
      - image: circleci/golang:1.11
    environment:
      - APP_NAME: goaccessor
      - GO111MODULE: "on"

commands:
  test:
    steps:
      - run: make test

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - go-module/setup:
          project_name: goaccessor
      - test

workflows:
  version: 2
  setup_and_deploy:
    jobs:
      - test
      - reviewdog/run:
          tag: 1.11.1-stretch
          working_directory: /go/src/github.com/timakin/goaccessor
          linters: golang.org/x/lint/golint github.com/kisielk/errcheck